#!/bin/bash

# atuin completion
if [ -n "$GENCOMPL_FPATH" ] && [[ -x "$(command -v atuin)" ]]; then
  mkdir -p "$GENCOMPL_FPATH"
  atuin gen-completions --shell zsh --out-dir "$GENCOMPL_FPATH"
fi

if [[ -x "$(command -v atuin)" ]]; then
  # you have to register atuin once and import _once_
  atuin sync || (if atuin login -u Mellbourn | grep "You are already logged in! Please run 'atuin logout' if you wish to login again"; then
    atuin logout
    atuin login -u Mellbourn
  fi && atuin import auto)
fi