#!/bin/bash

version_gte() {
  printf '%s\n%s' "$1" "$2" | sort -C -V -r
}
if [ -x "$(command -v cargo)" ] && version_gte "$(cargo --version | cut -d " " -f2)" 1.0.0; then
  cargo install --verbose cargo-update || true
  cargo install --verbose termimage || true
  if ! [ -x "$(command -v atuin)" ]; then
    cargo install --verbose atuin || true
  fi
  # not working anymore?
  if [ -f ~/.cargo/bin/cargo-install-update ]; then
    set +e
    cargo install-update -a
    set -e
  fi
  if [ -f ~/.cargo/bin/cargo-install-update-config ]; then
    mv ~/.cargo/bin/cargo-install-update-config ~/.cargo/bin/cargo-install-update-configure
  fi
fi
