#!/bin/bash

# fonts
if [[ $(uname) == 'Darwin' || -n $UBUNTU_DESKTOP ]]; then
  if [[ $(uname) == 'Darwin' ]]; then
    FONT_DIRECTORY=~/Library/Fonts
  else
    mkdir -p ~/.local/share/fonts
    FONT_DIRECTORY=~/.local/share/fonts
  fi
fi
