#!/bin/bash

# Install `zinit` if not installed
if [ ! -d ~/.zinit ]; then
  mkdir ~/.zinit
  chmod go-w ~/.zinit # to avoid insecure directories complaint
  git clone https://github.com/zdharma-continuum/zinit.git ~/.zinit/bin
else
  # when all computers have switchted to zdharma-continuum, this can be removed
  pushd ~/.zinit/bin
  git remote set-url origin https://github.com/zdharma-continuum/zinit.git
  popd
fi

if [ -x "$(command -v zsh)" ]; then
  zsh -ic "zinit self-update; zinit update --all; zinit cclear"
  zsh -ic "zinit delete -y zdharma/fast-syntax-highlighting | true"
  zsh -ic "zinit delete -y zdharma/history-search-multi-word | true"
  zsh -ic "zinit delete -y zdharma/null | true"
  zsh -ic "zinit delete -y zdharma/zsh-diff-so-fancy | true"
fi
