#!/usr/bin/env zsh

# --- Path 設定 ---
typeset -gU path fpath
path=(
    ${HOME}/.local/bin(N-/)
    $path
    /usr/local/{,s}bin(N-/)
)
fpath=(
    $fpath
    ${HOME}/.local/bin/common(N-/)
)

# --- Sheldon 插件載入 ---
if (( $+commands[sheldon] )); then
    eval "$(sheldon source)"
fi

# --- Oh My Posh 提示符 ---
if (( $+commands[oh-my-posh] )); then
    eval "$(oh-my-posh init zsh --config ${HOME}/.config/oh-my-posh/config.yaml)"
fi
